$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("@echo off")
[void]$sb.AppendLine("chcp 65001 > nul")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("setlocal enabledelayedexpansion")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("echo ========================================")
[void]$sb.AppendLine("echo   Tantan System Launcher")
[void]$sb.AppendLine("echo ========================================")
[void]$sb.AppendLine("echo.")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("set ""BACKEND_PORT=8000""")
[void]$sb.AppendLine("set ""BACKEND_MAX_PORT=8010""")
[void]$sb.AppendLine("set ""FRONTEND_PORT=3000""")
[void]$sb.AppendLine("set ""FRONTEND_MAX_PORT=3010""")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("set ""PROJECT_ROOT=%~dp0""")
[void]$sb.AppendLine("set ""PROJECT_ROOT=%PROJECT_ROOT:~0,-1%""")
[void]$sb.AppendLine("")
[void]$sb.AppendLine(":CHECK_BACKEND")
[void]$sb.AppendLine("netstat -ano 2^>nul ^| findstr /r ""^.*:%BACKEND_PORT%.*LISTENING"" > nul")
[void]$sb.AppendLine("if !errorlevel! equ 0 (")
[void]$sb.AppendLine("    if %BACKEND_PORT% lss %BACKEND_MAX_PORT% (")
[void]$sb.AppendLine("        echo [Backend] Port %BACKEND_PORT% in use, trying next...")
[void]$sb.AppendLine("        set /a BACKEND_PORT+=1")
[void]$sb.AppendLine("        goto CHECK_BACKEND")
[void]$sb.AppendLine("    ) else (")
[void]$sb.AppendLine("        echo [ERROR] All backend ports (8000-8010) are in use")
[void]$sb.AppendLine("        exit /b 1")
[void]$sb.AppendLine("    )")
[void]$sb.AppendLine(")")
[void]$sb.AppendLine("")
[void]$sb.AppendLine(":CHECK_FRONTEND")
[void]$sb.AppendLine("netstat -ano 2^>nul ^| findstr /r ""^.*:%FRONTEND_PORT%.*LISTENING"" > nul")
[void]$sb.AppendLine("if !errorlevel! equ 0 (")
[void]$sb.AppendLine("    if %FRONTEND_PORT% lss %FRONTEND_MAX_PORT% (")
[void]$sb.AppendLine("        echo [Frontend] Port %FRONTEND_PORT% in use, trying next...")
[void]$sb.AppendLine("        set /a FRONTEND_PORT+=1")
[void]$sb.AppendLine("        goto CHECK_FRONTEND")
[void]$sb.AppendLine("    ) else (")
[void]$sb.AppendLine("        echo [ERROR] All frontend ports (3000-3010) are in use")
[void]$sb.AppendLine("        exit /b 1")
[void]$sb.AppendLine("    )")
[void]$sb.AppendLine(")")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("echo [Backend] Using port: %BACKEND_PORT%")
[void]$sb.AppendLine("echo [Frontend] Using port: %FRONTEND_PORT%")
[void]$sb.AppendLine("echo.")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("echo [Config] Updating frontend API proxy...")
[void]$sb.AppendLine("cd /d ""%PROJECT_ROOT%\frontend""")
[void]$sb.AppendLine("powershell -Command ""(Get-Content next.config.js) -replace 'localhost:d+', 'localhost:%BACKEND_PORT%' | Set-Content next.config.js""")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("echo [Backend] Starting...")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("set ""PYTHONPATH=%PROJECT_ROOT%\..;%PYTHONPATH%""")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("cd /d ""%PROJECT_ROOT%\backend""")
[void]$sb.AppendLine("if exist ""venv\Scripts\activate.bat"" (")
[void]$sb.AppendLine("    call venv\Scripts\activate.bat")
[void]$sb.AppendLine(")")
[void]$sb.AppendLine("start ""Backend-%BACKEND_PORT%"" /min cmd /c ""cd /d \""%PROJECT_ROOT%\..\"" && python -m tantan.backend.main --port %BACKEND_PORT%""")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("timeout /t 3 /nobreak > nul")
[void]$sb.AppendLine("echo [Backend] Running in background (port %BACKEND_PORT%)")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("echo [Frontend] Starting...")
[void]$sb.AppendLine("cd /d ""%PROJECT_ROOT%\frontend""")
[void]$sb.AppendLine("start ""Frontend-%FRONTEND_PORT%"" cmd /c ""npm run dev""")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("timeout /t 5 /nobreak > nul")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("echo [Browser] Opening http://localhost:%FRONTEND_PORT%")
[void]$sb.AppendLine("start http://localhost:%FRONTEND_PORT%")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("echo.")
[void]$sb.AppendLine("echo ========================================")
[void]$sb.AppendLine("echo   Done!")
[void]$sb.AppendLine("echo   Backend: http://localhost:%BACKEND_PORT%")
[void]$sb.AppendLine("echo   Frontend: http://localhost:%FRONTEND_PORT%")
[void]$sb.AppendLine("echo ========================================")

$content = $sb.ToString()
[System.IO.File]::WriteAllText("C:\Users\25776\Desktop\work\claude_workspace\tantan\tantan\start.bat", $content)
Write-Output "Done"