"""后端中文字段名 -> 前端英文字段名 映射表"""
# ⚠️ 此文件由 `python -m tantan.backend.scripts.codegen_field_schema` 自动生成
# 不要手动编辑！改 `tantan/shared/field_schema.json` 后重跑 codegen。

from typing import Dict, Any



# 后端字段名到前端字段名的映射（由 codegen 自动生成）
BACKEND_TO_FRONTEND_FIELD_MAP: Dict[str, str] = {
    # Section 1 - 基本信息
    "企业名称": "enterpriseName",
    "所属行业": "industry",
    "联系人": "contact",
    "联系方式": "contactPhone",
    "生产地址": "productionAddress",
    "核算年份": "reportingYear",
    "核算周期说明": "reportingPeriod",
    "是否为自然年（1月1日-12月31日）": "isCalendarYear",
    # Section 2 - 产品
    "PCF核算目标产品名称": "targetProductName",
    "是否为生产工厂唯一产品": "isOnlyProduct",
    "其他产品1名称": "otherProduct1Name",
    "其他产品2名称": "otherProduct2Name",
    "其他产品3名称": "otherProduct3Name",
    "其他产品4名称": "otherProduct4Name",
    "其他产品5名称": "otherProduct5Name",
    "其他产品超过5种的说明": "otherProductsNote",
    "计量单位": "unit",
    "目标产品产线内是否有副产品": "hasByproduct",
    "副产品1名称": "byproduct1Name",
    "副产品2名称": "byproduct2Name",
    "副产品3名称": "byproduct3Name",
    "副产品4名称": "byproduct4Name",
    "副产品5名称": "byproduct5Name",
    "副产品超过5种的说明": "byproductsNote",
    # Section 3 - 燃料使用
    "生产用锅炉燃料": "boilerFuel",
    "专用废气焚烧炉燃料": "wasteIncineratorFuel",
    "危废焚烧炉燃料": "hazardousWasteBurnerFuel",
    "发电机燃料": "generatorFuel",
    "食堂炉灶燃料": "canteenFuel",
    "厂内转运叉车燃料": "forkliftFuel",
    "自有商务车92#": "commercialVehicle92",
    "自有商务车95#": "commercialVehicle95",
    "自有商务车98#": "commercialVehicle98",
    "自有道路车辆燃料-柴油": "roadVehicleDiesel",
    "切割、焊接燃料": "weldingFuel",
    "燃料类型": "fuelType",
    "使用量": "amount",
    "单位": "unit",
    "实测热值": "measuredCalorific",
    "热值单位": "calorificUnit",
    "燃料类型": "fuelType",
    "使用量": "amount",
    "单位": "unit",
    "燃料类型": "fuelType",
    "使用量": "amount",
    "单位": "unit",
    "燃料类型": "fuelType",
    "使用量": "amount",
    "单位": "unit",
    "燃料类型": "fuelType",
    "使用量": "amount",
    "单位": "unit",
    "燃料类型": "fuelType",
    "使用量": "amount",
    "单位": "unit",
    "燃料类型": "fuelType",
    "燃料类型": "fuelType",
    "燃料类型": "fuelType",
    "燃料类型": "fuelType",
    "燃料类型": "fuelType",
    # Section 4 - 电力、热力使用
    "全厂用电": "totalElectricityMeasurable",
    "全厂用电量": "totalElectricityAmount",
    "生产用电": "productionElectricityMeasurable",
    "生产用电量": "productionElectricityAmount",
    "行政办公用电": "officeElectricityMeasurable",
    "行政办公用电量": "officeElectricityAmount",
    "目标产品产线用电": "productLineElectricityMeasurable",
    "目标产品产线用电量": "productLineElectricityAmount",
    "单耗用电": "unitConsumptionElectricityMeasurable",
    "单耗用电量": "unitConsumptionElectricityAmount",
    "光伏发电量": "solarGeneration",
    "光伏发电配置": "solarConfig",
    "是否购买绿证": "greenCertificate",
    "绿证购买量": "greenCertificateAmount",
    "是否购买排放权益": "emissionRights",
    "排放权益购买量": "emissionRightsAmount",
    "蒸汽温度": "steamTemperature",
    "蒸汽压力": "steamPressure",
    "全厂用蒸汽": "totalSteamMeasurable",
    "全厂蒸汽量": "totalSteamAmount",
    "生产用蒸汽": "productionSteamMeasurable",
    "生产蒸汽量": "productionSteamAmount",
    "行政类用蒸汽": "officeSteamMeasurable",
    "行政类蒸汽量": "officeSteamAmount",
    "目标产品产线用蒸汽": "productLineSteamMeasurable",
    "目标产品产线蒸汽量": "productLineSteamAmount",
    "单耗用蒸汽": "unitConsumptionSteamMeasurable",
    "单耗蒸汽量": "unitConsumptionSteamAmount",
    # Section 5 - 制冷剂使用
    "空调制冷剂": "airConditioners",
    "冷冻机制冷剂": "freezers",
    "设备名称": "equipmentName",
    "标号": "refrigerantNo",
    "填充量": "fillAmount",
    "设备名称": "equipmentName",
    "标号": "refrigerantNo",
    "填充量": "fillAmount",
    # Section 6 - 其他散逸类排放
    "CO2灭火器填充总量": "co2Extinguisher",
    "核算期内员工总工时": "employeeHours",
    # Section 7 - 三废处理
    "废水处理方式": "wastewaterTreatmentMethod",
    "废水处理量": "wastewaterAmount",
    "目标产品产线废水": "productLineWastewater",
    "COD浓度": "codConcentration",
    "污水处理药剂1": "wastewaterAgent1",
    "污水处理药剂2": "wastewaterAgent2",
    "污水处理药剂3": "wastewaterAgent3",
    "废气处理方式": "exhaustGasTreatmentMethod",
    "危废委外焚烧总量": "outsourcedIncinerationTotal",
    "危废委外焚烧目标产品产线分解": "outsourcedIncinerationProductLine",
    "危废自行焚烧总量": "selfIncinerationTotal",
    "危废自行焚烧目标产品产线分解": "selfIncinerationProductLine",
    "危废委外资源化总量": "outsourcedRecyclingTotal",
    "危废委外资源化目标产品产线分解": "outsourcedRecyclingProductLine",
    "危废自行资源化总量": "selfRecyclingTotal",
    "危废自行资源化目标产品产线分解": "selfRecyclingProductLine",
    "烟气处理药剂1": "flueGasAgent1",
    "烟气处理药剂2": "flueGasAgent2",
    "烟气处理药剂3": "flueGasAgent3",
    "烟气处理药剂4": "flueGasAgent4",
    # Section 8 - 原材料使用
    "PCF核算目标产品生产工艺流程文字描述": "productionProcess",
    "原材料": "rawMaterials",
    "供应商": "suppliers",
    "名称": "name",
    "规格": "spec",
    "使用量": "amount",
    "单位": "unit",
    "名称": "name",
    "品类": "category",
    "运输方式": "transportMode",
    "运距": "transportDistance",
    # Section 9 - 生产耗材
    "新鲜水": "freshWater",
    "新鲜水使用量": "freshWaterUsage",
    "氮气": "nitrogen",
    "统计口径": "freshWaterCaliber",
    "使用量": "freshWaterAmount",
    "单位": "freshWaterUnit",
    "统计口径": "nitrogenCaliber",
    "使用量": "nitrogenAmount",
    "单位": "nitrogenUnit",
}
